"""Curated retrospective public chronology, NOT a record of tracker ingestion."""
import json
from pathlib import Path
rows = [
('2017-06-14','Calibration was already a measurable property','paper','On Calibration of Modern Neural Networks','https://proceedings.mlr.press/v70/guo17a.html','Published research date; no Jev relationship asserted','Probability quality needs evaluation; an API confidence field is not calibration evidence.'),
('2019-08-31','Classification without a task-specific training set','paper','Benchmarking Zero-shot Text Classification','https://arxiv.org/abs/1909.00161','arXiv v1 submission date, verified on the primary record','Zero-shot classification is prior art, not itself the new mechanism.'),
('2025-03-04','RL for calibrated confidence expression','paper','Rewarding Doubt','https://arxiv.org/abs/2503.02623','arXiv v1 submission date; later versions exist','An earlier reward-design route toward calibrated probabilities; not evidence of TypeSafe’s recipe.'),
('2025-07-22','Correctness plus a calibration reward','paper','Beyond Binary Rewards / RLCR','https://arxiv.org/abs/2507.16806','arXiv v1 submission date; later versions exist','RLCR is related research, not the same named method as TypeSafe RLCD.'),
('2025-08-11','Generalist lightweight classification','paper','GLiClass','https://arxiv.org/abs/2508.07662v1','arXiv v1 submission date','Dynamic labels and efficient discrimination were visible before Jev.'),
('2026-04-01','A direct company-specific signal','company','Founders You Should Know — March 25 showcase recap','https://newsletter.foundersysk.com/p/founders-you-should-know-march-25th','Organizer post dated April 1; event March 25; historical page bytes not archived here','TypeSafe was described as building models for automation rather than conversation.'),
('2026-06-19','The founder’s automation critique was public','company','AI: Too Good to Be True, Too Bad to Be Useful','https://typesafe.ai/blog/ai-too-good-to-be-true-too-bad-to-be-useful-typesafe-ai','Current company page date; embedded video transcript not independently acquired','Useful watch signal, not evidence of the unreleased architecture or economics.'),
('2026-07-31','The calibrated-decision direction was explicit','company','AI Engineer — What’s next after RLHF?','https://ai.engineer/talks/cJ0EOzey--o-whats-next-after-rlhf','July 31 video date is secondary-corroborated; official transcript content verified; raw upload timestamp not independently retrieved','Around 16:19 the founder describes models optimized for calibrated decisions. Suitable for a watch before a paper existed.'),
('2026-09-10','A task-first thesis, just before launch','company','The Bitterest Lesson','https://typesafe.ai/blog/bitterest-lesson','Current company page date; not proof of historical indexing','The automation task framing was visible, but detailed Jev capabilities were not established.'),
('2026-09-15','Jev early-access launch','launch','Introducing System One Models & Jev','https://typesafe.ai/blog/introducing-system-one-models-and-jev','Official dated launch page','A new product and vendor mechanism claim; performance and calibration still need independent workload testing.'),
('2026-09-16','An additional integration route','launch','Jev available through Vercel AI Gateway','https://vercel.com/changelog/typesafe-ai-jev-now-available-on-ai-gateway','Official dated changelog','AI SDK evaluation interface and request privacy controls; not automatic enterprise approval.')]
out = {'warning':'Retrospective source discovery, not an ingestion audit. Actual tracker first-seen times, queries and rejection records remain UNKNOWN. A displayed publication date does not prove that a crawler could retrieve the same content then.',
       'signals':[dict(id=f'SIG-{i:02}',date=d,title=t,kind=k,source=s,url=u,date_basis=b,implication=m,tracker_ingestion='UNKNOWN') for i,(d,t,k,s,u,b,m) in enumerate(rows,1)]}
root=Path(__file__).resolve().parents[1]
(root/'data/signals.json').write_text(json.dumps(out,indent=2)+'\n')
