'use strict';
const $ = id => document.getElementById(id);
const state = {config:null,cases:[],packs:{},pack:'supply',caseId:'S01',receipt:null,busy:false};
const names = {issue:'Primary exception',owner:'Investigating team',severity:'Consequence level',sufficient:'Evidence sufficient',contradiction:'Material contradiction',next_evidence:'Next evidence to request'};
const routes = {VERIFY_SOURCE:['Verify the source','A trusted source check is required before routing.'],REFRESH_EVIDENCE:['Refresh the evidence','The evidence expired. A confident old answer cannot make it current.'],HUMAN_REVIEW:['Human review','A policy boundary or uncertain judgment requires a person.'],REQUEST_EVIDENCE:['Repair the evidence','Ask for a specific missing or conflicting piece of evidence before proceeding.'],ROUTE_TO_TEAM:['Recommend a team','The illustrative policy permits a team recommendation. No external action is taken.']};
const esc = value => String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function error(text){$('error').textContent=text;$('error').hidden=!text;}
function setBusy(b){state.busy=b;$('run').disabled=b;$('reconsider').disabled=b||!state.receipt;$('evaluate').disabled=b;$('mode').disabled=b;document.querySelectorAll('.case,.domains button').forEach(x=>x.disabled=b);}
async function api(path,body){const options=body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Token':state.config.session_token},body:JSON.stringify(body)};const r=await fetch(path,options);const data=await r.json();if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data;}
function currentCase(){return state.cases.find(c=>c.id===state.caseId);}
function provenance(){const p=state.receipt?.provenance;const live=p?.kind==='live_typesafe';$('provenance').classList.toggle('live',live);$('provenance').textContent=live?`Live TypeSafe result · ${state.receipt.response.model} · ${p.latency_ms.toFixed(0)} ms client-observed · Cost estimate, not an invoice`:'Synthetic replay · Authored teaching probabilities · No Jev API call';}
function renderDomains(){$('domains').innerHTML=Object.entries(state.packs).map(([id,p])=>`<button data-pack="${esc(id)}" class="${id===state.pack?'active':''}" aria-pressed="${id===state.pack}">${esc(p.name)}<span>${esc(p.subtitle)}</span></button>`).join('');$('domains').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.pack=b.dataset.pack;selectCase(state.cases.find(c=>c.pack===state.pack).id);renderDomains();});}
function renderQueue(){$('cases').innerHTML=state.cases.filter(c=>c.pack===state.pack).map(c=>`<button class="case ${c.id===state.caseId?'active':''}" data-case="${esc(c.id)}" aria-pressed="${c.id===state.caseId}"><span class="mono">${esc(c.id)}</span>${esc(c.title)}</button>`).join('');$('cases').querySelectorAll('button').forEach(b=>b.onclick=()=>selectCase(b.dataset.case));}
function selectCase(id){state.caseId=id;state.receipt=null;error('');$('variant').value='original';renderQueue();const c=currentCase();$('caseId').textContent=c.id;$('caseTitle').textContent=c.title;$('message').textContent=c.state.message;$('evidence').innerHTML=c.state.evidence.map(e=>`<div class="source"><strong>${esc(e.id)}</strong>${esc(e.text)}</div>`).join('');$('route').textContent='Ready to inspect';$('routeText').textContent='Run this case to inspect six small judgments and the routing policy.';$('decisionMetrics').innerHTML='';$('nextEvidence').innerHTML='';$('answers').innerHTML='<p class="empty">The probability distributions will appear here.</p>';$('trace').innerHTML='';$('raw').textContent='Run a case first.';$('callCount').textContent='No call yet';$('export').disabled=true;$('reconsider').disabled=true;provenance();}
function metric(label,value){return `<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;}
function renderReceipt(){const r=state.receipt,d=r.decision,p=r.provenance;provenance();$('route').textContent=routes[d.route][0];$('routeText').textContent=routes[d.route][1];$('callCount').textContent=r.additional_model_calls?`${r.additional_model_calls} model call`:'0 new model calls';$('decisionMetrics').innerHTML=metric('Suggested owner',d.owner)+metric('Top-owner probability',`${(d.owner_probability*100).toFixed(0)}%`)+metric('Critical consequence probability',`${(d.critical_probability*100).toFixed(0)}%`);if(p.kind==='live_typesafe'){$('decisionMetrics').innerHTML+=metric('Observed input tokens',p.usage.input_tokens)+metric('Estimated inference cost',p.estimated_cost_usd===null?'Unknown':'$'+p.estimated_cost_usd.toFixed(7));}const evidence=state.packs[state.pack].evidence[d.next_evidence];$('nextEvidence').innerHTML=`<h3>Next evidence candidate</h3><p>${esc(evidence)}</p>`;$('answers').innerHTML=Object.entries(r.response.answers).map(([id,a])=>{const v=a.type==='choice'?a.choice:a.type==='noul'?a.noul.toFixed(3):a.score.toFixed(2);const probs=a.type==='noul'?{yes:a.noul,no:1-a.noul}:a.probabilities;return `<details><summary><span class="answer-head"><span class="answer-name"><span class="type">${esc(a.type)}</span>${esc(names[id])}</span><span class="answer-value">${esc(v)}</span></span></summary><div class="distribution">${Object.entries(probs).map(([k,val])=>`<div class="prob-row"><span>${esc(a.type==='score'?`${k}: ${a.legend[k]}`:k)}</span><meter min="0" max="1" value="${val}" aria-label="${esc(k)} probability ${val}"></meter><span>${(val*100).toFixed(0)}%</span></div>`).join('')}<p class="question-copy">${esc(r.request.questions[id].instructions)}</p>${a.confidence!==undefined?`<p class="small">Vendor confidence / distribution concentration: ${a.confidence.toFixed(3)}. This is not a measured probability of correctness.</p>`:'<p class="small">Noul reports the probability of yes. It has no separate confidence statistic.</p>'}</div></details>`;}).join('');$('trace').innerHTML=d.trace.map(t=>`<li class="${t.matched?'matched':''}"><code>${esc(t.rule)} · ${t.matched?'triggered':'not triggered'}</code>${esc(t.explanation)}</li>`).join('');$('raw').textContent=JSON.stringify(r,null,2);$('export').disabled=false;$('reconsider').disabled=false;}
async function run(){error('');setBusy(true);try{if($('mode').value==='live'&&!state.config.live_enabled)throw new Error('Live mode is not configured. Open Connect Jev for the server-side setup.');state.receipt=await api('/api/run',{case_id:state.caseId,mode:$('mode').value,threshold:Number($('threshold').value),consent:$('consent').checked});renderReceipt();}catch(e){error(e.message+(state.receipt?' The previous result remains visible; no new result was produced.':''));}finally{setBusy(false);}}
async function reconsider(){if(!state.receipt)return;error('');setBusy(true);try{state.receipt=await api('/api/reconsider',{receipt_id:state.receipt.receipt_id,threshold:Number($('threshold').value),variant:$('variant').value});renderReceipt();}catch(e){error(e.message);}finally{setBusy(false);}}
function tab(id){document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!==id);document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));}
async function evaluate(){setBusy(true);try{const r=await api('/api/evaluate',{});$('evalResults').innerHTML=`<div class="eval-warning"><p>${esc(r.warning)}</p></div><h2>Owner classification · authored fixtures only</h2><div class="table-wrap"><table><thead><tr><th>Scenario</th><th>Cases</th><th>Accuracy</th><th>Brier ↓</th><th>ECE ↓</th></tr></thead><tbody>${Object.entries(r.by_pack).map(([pack,m])=>`<tr><td>${esc(state.packs[pack].name)}</td><td>${m.n}</td><td>${(m.accuracy*100).toFixed(0)}%</td><td>${m.brier.toFixed(3)}</td><td>${m.ece_10.toFixed(3)}</td></tr>`).join('')}</tbody></table></div><p class="small">${esc(r.overall.definition)}</p><h2>Selective error changes with coverage</h2><p>Only the owner-probability threshold is varied below. This is not the complete routing policy and is not a deployment risk estimate.</p><div class="table-wrap"><table><thead><tr><th>Threshold</th><th>Accepted</th><th>Coverage</th><th>Error among accepted</th></tr></thead><tbody>${r.overall.risk_coverage.map(x=>`<tr><td>${x.threshold.toFixed(2)}</td><td>${x.accepted}</td><td>${(x.coverage*100).toFixed(0)}%</td><td>${x.error_rate===null?'No accepted cases':(x.error_rate*100).toFixed(1)+'%'}</td></tr>`).join('')}</tbody></table></div><h2>What each case is teaching</h2><ul class="eval-notes">${Object.entries(r.notes).map(([id,n])=>`<li><strong>${esc(id)}</strong> · ${esc(n)}</li>`).join('')}</ul>`;}catch(e){$('evalResults').textContent=e.message;}finally{setBusy(false);}}
async function init(){try{state.config=await api('/api/config');const data=await api('/api/cases');state.cases=data.cases;state.packs=data.packs;renderDomains();selectCase(state.caseId);$('liveStatus').textContent=state.config.live_enabled?`Server key and enable flag are present. API access is not yet verified. Model: ${state.config.model}; session attempt cap: ${state.config.live_attempt_limit}.`:'This server is currently offline-only. Your account is not connected to this process.';}catch(e){error('Could not initialize the local lab: '+e.message);}}
$('run').onclick=run;$('reconsider').onclick=reconsider;$('evaluate').onclick=evaluate;$('threshold').oninput=()=>{$('thresholdValue').textContent=Number($('threshold').value).toFixed(2);};$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state.receipt,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${state.caseId}-${state.receipt.provenance.kind}-receipt.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('setupButton').onclick=()=>$('setup').showModal();$('closeSetup').onclick=()=>$('setup').close();init();
